version: '3'

services:
  server1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"

  server2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4444:3333"